### ISSUE TITLE
Screen shaking when in high aspect ratio

### ISSUE THREAD

**Issue by ProphesorIks** [MCForsas/LibGdxVLE#1]
When aspect ratio is higher than aspect ratio of the level and the camera is bounded, the screen will start shaking intensely. Caused by camera position clamping.

**Comment by MCForsas** [comment]
Solved by stopping clamp methods from executing, when detected change aspect ratios.

**Comment by MCForsas** [comment]
Solved by stopping clamp methods from executing, when detected change aspect ratios.

**Comment by MCForsas** [comment]
After further investigation, it appears, that camera clamping isn't working anymore. Reverted code to the original. Issue remains

**Comment by ProphesorIks** [comment]
After further investigation, it appears, that camera clamping isn't working anymore. Reverted code to the original. Issue remains

**Comment by MCForsas** [comment]
Fixed by having camera always in the center of the screen when viewport has biger dimension than world does

**Comment by ProphesorIks** [comment]
Fixed by having camera always in the center of the screen when viewport has biger dimension than world does
